### PR TITLE
Add missing DescribeExportTasks

### PR DESCRIPTION
**Pull request by j2clerck**
Add missing DescribeExportTasks.
It is missing from the IAM Visual Editor as well.

*Issue #, if available:*

*Description of changes:*
Add missing DescribeExportTasks.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by carlasp** [comment]
Thank you for your feedback! I am checking this with the AWS Application Discovery Service writer, who will follow up.

**Comment by carlasp** [comment]
Hello again! We've reviewed your PR and you are correct. This page is automatically generated from the service’s files and we’re working with the teams to get it updated. When it’s ready, we’ll accept your pull request. Thanks for helping us make the docs better!

**Comment by stephswo** [comment]
We are still waiting on the Application Disovery team to update the source.

**Comment by stephswo** [comment]
I'm notifying the Application Discovery team again.

**Comment by stephswo** [comment]
I contacted the Application Discovery team again.

**Comment by stephswo** [comment]
I contacted them again. We have not forgotten about this issue.

**Comment by stephswo** [comment]
I confirmed that it's been fixed. Thanks for reporting this!

**Pull request merged**
