### PR TITLE
Clarified how Deny with NotResource Works In The Example

### PR DESCRIPTION
**Pull request by slimandslam**
Clarified how Deny with NotResource Works In The Example

*Issue #, if available:*

*Description of changes:* 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
The "clarification" is incorrect and this PR should be rejected.  The policy is a `deny` on `s3:*` and therefore only impacts S3. It does not impact other services such as "EC2, SQS, etc".

**Comment by slimandslam** [comment]
On that same page it says:

`When using NotResource, you should keep in mind that resources specified in this element are the only resources that are limited. This, in turn, means that all of the resources, including the resources in all other services, that are not listed are allowed if you use the Allow effect, or are denied if you use the Deny effect. `

It says " including the resources in all other services".  So, not only are the other unspecified S3 resources denied, but the resources "in all other services" are denied.  

Is that an error or is my clarification erroneous?

**Comment by 0xdabbad00** [comment]
I think the text you mentioned in that most recent comment needs clarification.  For example, I tested by having a user with `AdministratorAccess` and then giving them that policy. I was able to run `aws iam list-users` and `aws ec2 describe-instances` but not `aws s3 ls`.  

I then changed the policy on my user to:
```
{
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Deny",
        "Action": "*",
        "NotResource": [
            "arn:aws:s3:::HRBucket/Payroll",
            "arn:aws:s3:::HRBucket/Payroll/*"
        ]
    }
}
```
Note the action is now `*`.  With this policy I am now denied from calling `aws iam list-users`, `aws ec2 describe-instances`, or `aws s3 ls`.

**Comment by slimandslam** [comment]
Ok. I'll make another change to the page. Thanks @0xdabbad00 for the useful feedback. Please look for my followup pull.

**Pull request closed without merging**
