### PR TITLE
Switched from <code> tags to backticks

### PR DESCRIPTION
**Pull request by joeykilpatrick**
HTML \<code\> tags render on Github, but not in the AWS docs.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bonniekeller** [comment]
Thanks a lot for taking the time to submit a PR. We can't eliminate the code tags from our docs. We follow an internal style guide and these are the tags that we must use for this formatting to adhere to that style guide.

**Comment by joeykilpatrick** [comment]
Hi Bonnie, thanks for the response but I'm not sure I understand the reasoning. 

As far as I can tell, this seems to be the only place where `<code>` tags are used instead of backticks. Backticks are used throughout the file that is edited in this PR.

The reason for this PR isn't a difference of opinion in code-style, the problem is that `<code>` tags are not rendering properly on the docs. At [this link](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awscloudformation.html), the literal string "\<code\>AWS::EC2::Instance\</code\>" is being displayed instead of the correctly formatted string "`AWS::EC2::Instance`".

**Comment by bonniekeller** [comment]
Hi there, thanks for the clarification. I see the literal string on that page of the docs now. Unfortunately, this isn’t a page that we can edit. It gets overwritten every time we publish. I’ll have to cut a ticket to the EC2 team to ask them update the file that generates this page in the IAM docs. The code tags are what we would normally use in documentation, but there seems to be an issue with using that tag here.

**Comment by bonniekeller** [comment]
And I apologize, I meant to say CloudFormation, not EC2.

From: Keller, Bonnie
Sent: Friday, June 12, 2020 4:51 PM
To: 'awsdocs/iam-user-guide' <reply@reply.github.com>
Subject: RE: [awsdocs/iam-user-guide] Switched from <code> tags to backticks (#193)

Hi there, thanks for the clarification. I see the literal string on that page of the docs now. Unfortunately, this isn’t a page that we can edit. It gets overwritten every time we publish. I’ll have to cut a ticket to the EC2 team to ask them update the file that generates this page in the IAM docs. The code tags are what we would normally use in documentation, but there seems to be an issue with using that tag here.

**Pull request closed without merging**
