### PR TITLE
adds listing of aws service principals

### PR DESCRIPTION
**Pull request by shortjared**
*Issue #, if available:*

There is no single reference location to find all the service principals, previously I was maintaining a gist list for reference.

*Description of changes:*

Adds a single reference location to find all current service principals in a browser "find" friendly manner. Also adds a link in the policy reference for principals.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shortjared** [comment]
Cool, no problem. Might I suggest a page on what you would actually accept as part of the docs then?

This is something I have asked for a few times and never seen any action on, I readily did it myself when given the opportunity!

**Comment by stephswo** [comment]
It's been on the books for a while, but we don't have a date for it. There are some blockers that we're working on first. If you're internal to Amazon, send me a direct email (stephswo) and I can send you the link to the internal tracking item. Otherwise, just trust me when I say that not only is it on the radar, I am pushing hard to get it in the docs (and automated) by the end of the year.

**Comment by shortjared** [comment]
No worries, thank you for the explanation!

I would still appreciate a "what's accepted" listing on these docs in general before I go out of my way to produce anything else. If this page exists, apologies, but I haven't found it.

**Comment by jverce** [comment]
Has this been solved? Is there an issue we can upvote?
It's kind of painful to crawl the web to find examples we can use to set up something based on trial and error (e.g. who would've guessed that the Step Functions principal is `states.amazonaws.com` and not `stepfunctions.amazonaws.com`?).

**Pull request closed without merging**
